#!/usr/bin/env python3
"""Generate the EYAIDashPayload Script Include from the live /overview operation.

The dashboard originally fetched its data over XHR. That turns out to be
unreliable from an interactive ServiceNow session on this instance - the same
Scripted REST call that answers in ~1s over basic auth hangs indefinitely when
issued from a logged-in browser, and so does the platform's own Table API, so it
is not something our resource can fix. The page therefore computes its payload
server-side through Jelly instead, and XHR is demoted to refresh-only.

Rather than retype the engine (and risk it drifting from the endpoint), this
lifts the operation script that is already deployed and wraps it in a class.

Usage: build_payload_include.py <netrc-file>
"""

import json
import subprocess
import sys
from pathlib import Path

INSTANCE = "eypocinst.service-now.com"
OVERVIEW_OP = "2a70ae3b33d28390c63690834d5c7b47"
HERE = Path(__file__).parent


def curl(netrc, method, url, body=None):
    tmp = HERE / ".payload.json"
    cmd = ["curl", "-s", "--netrc-file", netrc, "-X", method, url,
           "-H", "Accept: application/json"]
    if body is not None:
        tmp.write_text(json.dumps(body))
        cmd += ["-H", "Content-Type: application/json", "-d", f"@{tmp}"]
    out = subprocess.run(cmd, capture_output=True, text=True).stdout
    tmp.unlink(missing_ok=True)
    return json.loads(out)


def main():
    netrc = sys.argv[1]
    op = curl(netrc, "GET", f"https://{INSTANCE}/api/now/table/sys_ws_operation/"
                            f"{OVERVIEW_OP}?sysparm_fields=operation_script")
    src = op["result"]["operation_script"]

    # Everything from the top of the operation down to where it answers is the
    # engine; the request/response plumbing on either side is what has to change.
    start = src.index("{") + 1
    end = src.index("response.setStatus(200);")
    engine = src[start:end]

    engine = engine.replace(
        "var table = request.queryParams.table ? request.queryParams.table[0] : 'incident';",
        "table = table || 'incident';")
    engine = engine.replace(
        "var months = request.queryParams.months ? "
        "parseInt(request.queryParams.months[0], 10) : 12;",
        "months = parseInt(months, 10) || 12;")

    body = src[end:].replace("response.setStatus(200);", "").replace(
        "response.setBody(", "return (").rstrip()
    body = body[:body.rindex("})(request, response);")].rstrip()

    include = f'''var EYAIDashPayload = Class.create();
EYAIDashPayload.prototype = {{
    initialize: function () {{}},

    /* Generated by poc/servicenow/build_payload_include.py from the deployed
       /overview operation - edit that endpoint and regenerate, do not hand-edit,
       or the page and the API will drift apart. */
    overview: function (table, months) {{
{engine}
{body}
    }},

    /* Base64 so the result can ride in an HTML attribute without any quoting or
       entity question: JSON is full of characters that an attribute is not. */
    overviewB64: function (table, months) {{
        return GlideStringUtil.base64Encode(JSON.stringify(this.overview(table, months)));
    }},

    type: 'EYAIDashPayload'
}};
'''

    found = curl(netrc, "GET", f"https://{INSTANCE}/api/now/table/sys_script_include"
                               "?sysparm_query=name=EYAIDashPayload&sysparm_fields=sys_id")
    rec = {"name": "EYAIDashPayload", "script": include, "active": "true",
           "access": "public", "api_name": "global.EYAIDashPayload",
           "client_callable": "false",
           "description": "Server-side dashboard payload for the ey_ai_dashboard UI Page."}

    if found["result"]:
        sid = found["result"][0]["sys_id"]
        curl(netrc, "PATCH", f"https://{INSTANCE}/api/now/table/sys_script_include/"
                             f"{sid}?sysparm_fields=sys_id", rec)
    else:
        sid = curl(netrc, "POST", f"https://{INSTANCE}/api/now/table/sys_script_include"
                                  "?sysparm_fields=sys_id", rec)["result"]["sys_id"]

    back = curl(netrc, "GET", f"https://{INSTANCE}/api/now/table/sys_script_include/"
                              f"{sid}?sysparm_fields=script")["result"]["script"]
    if back != include:
        sys.exit(f"MISMATCH - sent {len(include):,}, instance holds {len(back):,}")
    print(f"EYAIDashPayload deployed and verified ({len(include):,} bytes) sys_id={sid}")
    (HERE / "script-includes" / "EYAIDashPayload.js").parent.mkdir(exist_ok=True)
    (HERE / "script-includes" / "EYAIDashPayload.js").write_text(include)


if __name__ == "__main__":
    main()
